### ISSUE TITLE
Pubkey generation

### ISSUE THREAD

**Issue by vishal2241** [iceland2k14/bsgs#11]
Can it be modified somehow to write sequential pubkeys to external files at this much speed.

**Comment by iceland2k14** [comment]
No BSGS algo is used to check the keys since they are based on continuous subtraction.
Writing each and every key in output file will fill the buffer and make it horrible slow. Also Nobody have that much disk space in this whole planet to keep huge number of pubkey (Trillions) in disk. So the answer is NO.
