### ISSUE TITLE
what is the max. size of bpfile to create a bloom?

### ISSUE THREAD

**Issue by dextronomous** [iceland2k14/bsgs#12]
Hi Iceland2k14, i had a bpfile 4500000000 created 250gigs it had 45000 chunks
and did the 2_bloom.py got memory error, is there a limit to my bpfile,
 now i am at 1000 chunks just to see it that works,

**Comment by iceland2k14** [comment]
Thanks for trying it. I am amazed by the bPfile you created.
Now there is no limit for bPfile or bloom file. It just need sufficient RAM when they will be used in the next script for searching.

I tested only 3 types of bloom writing [  Full,  ](https://github.com/iceland2k14/bsgs/blob/main/bPfile_2_bloom.py#L112-L121)  and [  Line by Line,  ](https://github.com/iceland2k14/bsgs/blob/main/bPfile_2_bloom.py#L103-L110) and a [  Mix of these two](https://github.com/iceland2k14/bsgs/blob/main/bPfile_2_bloom.py#L82-L100)

Although i think the error you get in bloom creation is due to the reading of entire bPfile.
[Entire bPfile Reading](https://github.com/iceland2k14/bsgs/blob/main/bPfile_2_bloom.py#L78-L79)

I think, in such cases as yours with serious big Files, it needs to be modified to read and update everything within the function itself, line by line and not all together  [  bPfile Reading function  ](https://github.com/iceland2k14/bsgs/blob/main/bPfile_2_bloom.py#L66-L72)

Such case i did not anticipated earlier. But perhaps i will include it next time if needed.
