### ISSUE TITLE
Could you please Explain what is the main Work of FULLbpfile.bin

### ISSUE THREAD

**Issue by websonder** [iceland2k14/bsgs#4]
HI, i don't know about the Logic of this FULLbpfile.bin File, Could you please Explain, how it is work, what is the 
and also could you please explain how much time it will take to complete 02CEB6CBBCDBDF5EF7150682150F4CE2C6F4807B349827DCDBDD1F2EFA885A2630 -keyspace 800000000000000000000000000000:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

**Comment by albertobsd** [comment]
the bP files are Precalculated data to boost the speed of the process, is a bin file because the txt files need the double of space that bin files

About the time to scan the full 120 bit space acording to you current speed you can more o less determine that time according to the next table that I calculated:

```
Puzzle 120 @ 1 Terakeys/s :     21074771622667996 years
Puzzle 120 @ 1 Petakeys/s :     21074771622667 years
Puzzle 120 @ 1 Exakeys/s :      21074771622 years
Puzzle 120 @ 1 Zettakeys/s :    21074771 years
Puzzle 120 @ 1 Yottakeys/s :    21074 years
```

best regards!

**Comment by websonder** [comment]
means not possible

**Comment by albertobsd** [comment]
yes that is true, but the correct word is infeasible, due our lifetime and computer power of this day.

The best solucion is with math not brute force.

**Comment by bro79** [comment]
is it possible to make more threads (for example -t 8)?

**Comment by iceland2k14** [comment]
For using more number of threads ex. -t 8 please use Alberto Keyhunt tool. [Keyhunt](https://github.com/albertobsd/keyhunt)
